GCP_PROJECT_ID: ga4-multi-touch-attribution
BQ_DATASET: ga4_attribution
BQ_LOCATION: US
GA4_SOURCE_TABLE: bigquery-public-data.ga4_obfuscated_sample_ecommerce.events_*
START_DATE: 2020-11-01
END_DATE: 2021-01-31
MAXIMUM_BYTES_BILLED: 1000000000

