-- Review artifact only. These predicates are not applied in Phase 2A.
SELECT
  priority,
  proposed_channel,
  predicate_sql,
  rationale,
  'PROPOSED_NOT_APPROVED' AS approval_status
FROM UNNEST([
  STRUCT(1 AS priority, 'Direct' AS proposed_channel,
    "source_resolution_tier = 'Direct' OR LOWER(resolved_source) = '(direct)' OR LOWER(resolved_medium) = '(none)'" AS predicate_sql,
    'Preserve explicit Direct evidence before all other rules.' AS rationale),
  STRUCT(2, 'Paid Social',
    "REGEXP_CONTAINS(LOWER(COALESCE(resolved_medium, '')), r'^(paid[_ -]?social|social[_ -]?paid)$') OR (REGEXP_CONTAINS(LOWER(COALESCE(resolved_medium, '')), r'^(cpc|ppc|paidsearch|paid search|sem)$') AND REGEXP_CONTAINS(LOWER(COALESCE(resolved_source, '')), r'(^|\\.)(facebook\\.com|instagram\\.com|twitter\\.com|t\\.co|linkedin\\.com|pinterest\\.[a-z.]+|tiktok\\.com|youtube\\.com)$'))",
    'Paid-social evidence must precede generic paid-search medium matching.'),
  STRUCT(3, 'Paid Search',
    "REGEXP_CONTAINS(LOWER(COALESCE(resolved_medium, '')), r'^(cpc|ppc|paidsearch|paid search|sem)$')",
    'Classify remaining paid search media after Paid Social.'),
  STRUCT(4, 'Display',
    "REGEXP_CONTAINS(LOWER(COALESCE(resolved_medium, '')), r'^(display|banner|cpm|programmatic)$')",
    'Use explicit display media.'),
  STRUCT(5, 'Email',
    "REGEXP_CONTAINS(LOWER(COALESCE(resolved_medium, '')), r'^(email|e-mail|e_mail)$')",
    'Use explicit email media.'),
  STRUCT(6, 'Affiliates',
    "REGEXP_CONTAINS(LOWER(COALESCE(resolved_medium, '')), r'^affiliate(s)?$')",
    'Use explicit affiliate media.'),
  STRUCT(7, 'Organic Search',
    "REGEXP_CONTAINS(LOWER(COALESCE(resolved_medium, '')), r'^organic$')",
    'Use explicit organic-search medium.'),
  STRUCT(8, 'Organic Social',
    "REGEXP_CONTAINS(LOWER(COALESCE(resolved_medium, '')), r'^(social|social-network|social-media|sm)$') OR REGEXP_CONTAINS(LOWER(COALESCE(resolved_source, '')), r'(^|\\.)(facebook\\.com|instagram\\.com|twitter\\.com|t\\.co|linkedin\\.com|pinterest\\.[a-z.]+|tiktok\\.com|youtube\\.com)$')",
    'Classify non-paid social evidence after paid rules.'),
  STRUCT(9, 'Referral',
    "source_resolution_tier = 'external_referrer' OR LOWER(COALESCE(resolved_medium, '')) = 'referral'",
    'Referral is considered only after proposed internal domains are excluded.'),
  STRUCT(10, 'Unknown',
    "source_resolution_tier = 'Unknown' OR (resolved_source IS NULL AND resolved_medium IS NULL)",
    'Retain sessions without reliable source evidence as Unknown.'),
  STRUCT(11, 'Other',
    'TRUE',
    'Mutually exclusive terminal fallback for remaining values.')
]);
